### ISSUE TITLE
Json to Resx name field is not copying the correct value (Angular)

### ISSUE THREAD

**Issue by okrprograms** [locize/resx#1]
## 🐛 Bug Report

I am converting JSON to Resx XML, I am passing name, value, comment in the Json Object list. But when i get the resultant XML it does not map the name field value to name, Value and Comment field work properly but not the name. 

## To Reproduce

Pass the JSON object list to this function in Console the resultant XML will not map the name values to name in the XML
My JSON object list is like the below JSON list.

returned XML is like this name contain random number. 

```js
data = [{name: 'menuItemValue', value:'Weeks Per Year', comment:'Add DDI LM 19-09-2016'}]

js2resx(data, (err: any, res: any) => {
            // res is like xml
            console.log(res);
        })

result: 

<data name="816" xml:space="preserve">
    <value>Weeks Per Year</value>
    <comment>Add DDI LM 19-09-2016</comment>
  </data>
```

## Expected behavior

I want to have name field value from my JSON object list to the resultant name in the XML. like this below.

```js
<data name="menuItemValue" xml:space="preserve">
    <value>Weeks Per Year</value>
    <comment>Add DDI LM 19-09-2016</comment>
  </data>
```

## Your Environment
node v16
angular v13
windows 10

**Comment by adrai** [comment]
You're passing a wrong json.

Try: 

```js
js2resx({
  menuItemValue: {
    value: 'Weeks Per Year',
    comment: 'Add DDI LM 19-09-2016'
  }
}, (err, res) => {
  console.log(res)
})
```

**Comment by okrprograms** [comment]
> ```js
> {
>   menuItemValue: {
>     value: 'Weeks Per Year',
>     comment: 'Add DDI LM 19-09-2016'
>   }
> }
> ```

trying with that give me the error below 

Argument of type '{ menuItemValue: { value: string; comment: string; }; }' is not assignable to parameter of type 'ObjectOfStrings'

**Comment by adrai** [comment]
Can you please provide a reproducible example? It seems to work: https://codesandbox.io/s/interesting-violet-kc50k0?file=/src/index.js

**Comment by okrprograms** [comment]
thanks @adrai it worked.
I was not formatting my object properly. I was passing array, I have to pass object with dynamic properties name. One thing more I must initialize my object with 'any' type to overcome the  (type 'ObjectOfStrings') error which was occuring. 

the solution below for Angular users

```js
let jsonObjct : any = {
labelName: {value:"value here", comment: "comment here"}, 
labelName2:{value:"value here", comment: "comment here"}
}

js2resx(jsonObjct, (err: any, res: any) => {
            // res is like xml
            console.log(res);
})
```
the result will be proper now like expected. 

```
<data name="labelName" xml:space="preserve">
    <value>value here</value>
    <comment>comment here</comment>
  </data>
  <data name="labelName2" xml:space="preserve">
    <value>value here</value>
    <comment>comment here</comment>
  </data>
```
