### ISSUE TITLE
remove empty comment at js2resx

### ISSUE THREAD

**Issue by 8LWXpg** [locize/resx#3]
## 🚀 Feature Proposal

remove `<comment/>`

## Motivation

`<comment>` is removed instead of leaving blank at some resx files, making changes in file dff.

## Example

don't preserve empty comment as default or making an option for it.

**Comment by adrai** [comment]
I don't know exactly what you mean...
Can you create a test case (and PR that would address this)?

**Comment by 8LWXpg** [comment]
for example, an object like this where comment is empty string
```js
{
  name: { 
    value: 'value', 
    comment: '' 
  } 
}
```
will result in empty `comment` tag
```xml
<root>
  <data name="name" xml:space="preserve">
    <value>value</value>
    <comment/>
  </data>
</root>
```
I want that empty comment tag removed by default or by an option

**Comment by adrai** [comment]
that's consistent...

if you don't like that, you can loop your json and remove the comment property if its value is ''

**Comment by 8LWXpg** [comment]
yeah... I thought a little bit more, it should be done before calling the function.

sorry for the inconvenience.
